
export const emojis = ref([
  // 笑脸和情感
  { symbol: '😀', name: '大笑' },
  { symbol: '😃', name: '开心' },
  { symbol: '😄', name: '微笑' },
  { symbol: '😁', name: '笑嘻嘻' },
  { symbol: '😆', name: '笑哭了' },
  { symbol: '😅', name: '苦笑' },
  { symbol: '😂', name: '笑到哭' },
  { symbol: '🤣', name: '在地上笑' },
  { symbol: '😊', name: '羞涩微笑' },
  { symbol: '😇', name: '天使笑脸' },
  { symbol: '🙂', name: '微微一笑' },
  { symbol: '🙃', name: '颠倒笑脸' },
  { symbol: '😉', name: '眨眼' },
  { symbol: '😌', name: '松了口气' },
  { symbol: '😍', name: '爱心眼' },
  { symbol: '🥰', name: '爱心笑脸' },
  { symbol: '😘', name: '飞吻' },
  { symbol: '😗', name: '亲亲' },
  { symbol: '😙', name: '亲亲微笑' },
  { symbol: '😚', name: '闭眼亲亲' },
  { symbol: '😋', name: '好吃' },
  { symbol: '😛', name: '吐舌头' },
  { symbol: '😝', name: '闭眼吐舌' },
  { symbol: '😜', name: '眨眼吐舌' },
  { symbol: '🤪', name: '疯狂脸' },
  { symbol: '🤨', name: '挑眉' },
  { symbol: '🧐', name: '戴眼镜' },
  { symbol: '🤓', name: '书呆子' },
  { symbol: '😎', name: '酷' },
  { symbol: '🤩', name: '星星眼' },
  { symbol: '🥳', name: '派对脸' },
  { symbol: '😏', name: '得意' },
  { symbol: '😒', name: '不悦' },
  { symbol: '😞', name: '失望' },
  { symbol: '😔', name: '沉思' },
  { symbol: '😟', name: '担心' },
  { symbol: '😕', name: '困惑' },
  { symbol: '🙁', name: '微微难过' },
  { symbol: '☹️', name: '难过' },
  { symbol: '😣', name: '坚持' },
  { symbol: '😖', name: '困扰' },
  { symbol: '😫', name: '疲惫' },
  { symbol: '😩', name: '痛苦' },
  { symbol: '🥺', name: '恳求' },
  { symbol: '😢', name: '哭泣' },
  { symbol: '😭', name: '大哭' },
  { symbol: '😤', name: '生气' },
  { symbol: '😠', name: '愤怒' },
  { symbol: '😡', name: '暴怒' },
  { symbol: '🤬', name: '骂人' },
  { symbol: '🤯', name: '爆炸头' },
  { symbol: '😳', name: '脸红' },
  { symbol: '🥵', name: '热热' },
  { symbol: '🥶', name: '冷冷' },
  { symbol: '😱', name: '吓死了' },
  { symbol: '😨', name: '害怕' },
  { symbol: '😰', name: '冷汗' },
  { symbol: '😥', name: '失望但松了口气' },
  { symbol: '😓', name: '汗流浃背' },
  { symbol: '🤗', name: '拥抱' },
  { symbol: '🤔', name: '思考' },
  { symbol: '🤭', name: '捂嘴' },
  { symbol: '🤫', name: '嘘' },
  { symbol: '🤥', name: '说谎' },
  { symbol: '😶', name: '无语' },
  { symbol: '😐', name: '面无表情' },
  { symbol: '😑', name: '毫无感情' },
  { symbol: '😬', name: '做鬼脸' },
  { symbol: '🙄', name: '翻白眼' },
  { symbol: '😯', name: '惊讶' },
  { symbol: '😦', name: '啊' },
  { symbol: '😧', name: '痛苦' },
  { symbol: '😮', name: '哇' },
  { symbol: '😲', name: '震惊' },
  { symbol: '🥱', name: '打哈欠' },
  { symbol: '😴', name: '睡觉' },
  { symbol: '🤤', name: '流口水' },
  { symbol: '😪', name: '困倦' },
  { symbol: '😵', name: '晕头转向' },
  { symbol: '🤐', name: '闭嘴' },
  { symbol: '🥴', name: '晕乎乎' },
  { symbol: '🤢', name: '恶心' },
  { symbol: '🤮', name: '呕吐' },
  { symbol: '🤧', name: '打喷嚏' },
  { symbol: '😷', name: '口罩' },
  { symbol: '🤒', name: '温度计' },
  { symbol: '🤕', name: '绷带头' },
  { symbol: '🤑', name: '金钱眼' },
  { symbol: '🤠', name: '牛仔' },
  { symbol: '😈', name: '恶魔微笑' },
  { symbol: '👿', name: '小恶魔' },
  { symbol: '👹', name: '食人魔' },
  { symbol: '👺', name: '小妖精' },
  { symbol: '🤡', name: '小丑' },
  { symbol: '💩', name: '便便' },
  { symbol: '👻', name: '鬼魂' },
  { symbol: '💀', name: '骷髅' },
  { symbol: '☠️', name: '骷髅交叉' },
  { symbol: '👽', name: '外星人' },
  { symbol: '👾', name: '外星怪物' },
  { symbol: '🤖', name: '机器人' },
  { symbol: '🎃', name: '南瓜灯' },
  { symbol: '😺', name: '猫笑' },
  { symbol: '😸', name: '猫开心' },
  { symbol: '😹', name: '猫笑哭' },
  { symbol: '😻', name: '猫爱心眼' },
  { symbol: '😼', name: '猫冷笑' },
  { symbol: '😽', name: '猫亲亲' },
  { symbol: '🙀', name: '猫尖叫' },
  { symbol: '😿', name: '猫哭' },
  { symbol: '😾', name: '猫生气' },
  
  // 手势和身体部位
  { symbol: '👋', name: '挥手' },
  { symbol: '🤚', name: '手背' },
  { symbol: '🖐️', name: '手掌' },
  { symbol: '✋', name: '举手' },
  { symbol: '🖖', name: '瓦肯举手' },
  { symbol: '👌', name: 'OK' },
  { symbol: '🤏', name: '捏' },
  { symbol: '✌️', name: '胜利' },
  { symbol: '🤞', name: '交叉手指' },
  { symbol: '🤟', name: '我爱你' },
  { symbol: '🤘', name: '摇滚' },
  { symbol: '🤙', name: '打电话' },
  { symbol: '👈', name: '左指' },
  { symbol: '👉', name: '右指' },
  { symbol: '👆', name: '上指' },
  { symbol: '🖕', name: '中指' },
  { symbol: '👇', name: '下指' },
  { symbol: '👍', name: '点赞' },
  { symbol: '👎', name: '点踩' },
  { symbol: '✊', name: '拳头' },
  { symbol: '👊', name: '出拳' },
  { symbol: '🤛', name: '左拳' },
  { symbol: '🤜', name: '右拳' },
  { symbol: '👏', name: '鼓掌' },
  { symbol: '🙌', name: '举双手' },
  { symbol: '👐', name: '张开双手' },
  { symbol: '🤲', name: '双手合十' },
  { symbol: '🤝', name: '握手' },
  { symbol: '🙏', name: '祈祷' },
  { symbol: '✍️', name: '写字' },
  { symbol: '💅', name: '涂指甲' },
  { symbol: '🤳', name: '自拍' },
  { symbol: '💪', name: '肌肉' },
  { symbol: '🦾', name: '机械臂' },
  { symbol: '🦿', name: '机械腿' },
  { symbol: '🦵', name: '腿' },
  { symbol: '🦶', name: '脚' },
  { symbol: '👂', name: '耳朵' },
  { symbol: '🦻', name: '助听器' },
  { symbol: '👃', name: '鼻子' },
  { symbol: '🧠', name: '大脑' },
  { symbol: '🦷', name: '牙齿' },
  { symbol: '🦴', name: '骨头' },
  { symbol: '👀', name: '眼睛' },
  { symbol: '👁️', name: '眼睛' },
  { symbol: '👅', name: '舌头' },
  { symbol: '👄', name: '嘴巴' },
  
  // 心情和符号
  { symbol: '💋', name: '吻' },
  { symbol: '💘', name: '丘比特之箭' },
  { symbol: '💝', name: '礼盒心' },
  { symbol: '💖', name: '闪亮的心' },
  { symbol: '💗', name: '跳动的心' },
  { symbol: '💓', name: '心跳' },
  { symbol: '💞', name: '旋转的心' },
  { symbol: '💕', name: '两颗心' },
  { symbol: '💟', name: '心装饰' },
  { symbol: '❣️', name: '感叹号心' },
  { symbol: '💔', name: '心碎' },
  { symbol: '❤️', name: '红心' },
  { symbol: '🧡', name: '橙心' },
  { symbol: '💛', name: '黄心' },
  { symbol: '💚', name: '绿心' },
  { symbol: '💙', name: '蓝心' },
  { symbol: '💜', name: '紫心' },
  { symbol: '🤎', name: '棕心' },
  { symbol: '🖤', name: '黑心' },
  { symbol: '🤍', name: '白心' },
  
  // 天气和自然
  { symbol: '☀️', name: '太阳' },
  { symbol: '🌝', name: '满月' },
  { symbol: '🌞', name: '太阳笑脸' },
  { symbol: '⭐', name: '星星' },
  { symbol: '🌟', name: '闪亮星星' },
  { symbol: '🌠', name: '流星' },
  { symbol: '☁️', name: '云' },
  { symbol: '🌈', name: '彩虹' },
  { symbol: '⚡', name: '闪电' },
  { symbol: '❄️', name: '雪花' },
  { symbol: '☃️', name: '雪人' },
  { symbol: '⛄', name: '无雪雪人' },
  { symbol: '💧', name: '水滴' },
  { symbol: '💦', name: '汗滴' },
  { symbol: '☔', name: '雨伞' },
  { symbol: '🌊', name: '海浪' },
  
  // 植物和动物
  { symbol: '🐶', name: '狗' },
  { symbol: '🐱', name: '猫' },
  { symbol: '🐭', name: '老鼠' },
  { symbol: '🐹', name: '仓鼠' },
  { symbol: '🐰', name: '兔子' },
  { symbol: '🦊', name: '狐狸' },
  { symbol: '🐻', name: '熊' },
  { symbol: '🐼', name: '熊猫' },
  { symbol: '🐨', name: '考拉' },
  { symbol: '🐯', name: '老虎' },
  { symbol: '🦁', name: '狮子' },
  { symbol: '🐮', name: '牛' },
  { symbol: '🐷', name: '猪' },
  { symbol: '🐸', name: '青蛙' },
  { symbol: '🐵', name: '猴子' },
  { symbol: '🐔', name: '鸡' },
  { symbol: '🐧', name: '企鹅' },
  { symbol: '🐦', name: '鸟' },
  { symbol: '🐤', name: '小鸟' },
  { symbol: '🦄', name: '独角兽' },
  { symbol: '🐝', name: '蜜蜂' },
  { symbol: '🐛', name: '虫子' },
  { symbol: '🦋', name: '蝴蝶' },
  { symbol: '🐌', name: '蜗牛' },
  { symbol: '🐞', name: '瓢虫' },
  { symbol: '🐜', name: '蚂蚁' },
  { symbol: '🦟', name: '蚊子' },
  { symbol: '🦗', name: '蟋蟀' },
  { symbol: '🕷️', name: '蜘蛛' },
  { symbol: '🦂', name: '蝎子' },
  { symbol: '🐢', name: '乌龟' },
  { symbol: '🐍', name: '蛇' },
  { symbol: '🦎', name: '蜥蜴' },
  { symbol: '🦖', name: '霸王龙' },
  { symbol: '🦕', name: '恐龙' },
  { symbol: '🐙', name: '章鱼' },
  { symbol: '🦑', name: '鱿鱼' },
  { symbol: '🦐', name: '虾' },
  { symbol: '🦞', name: '龙虾' },
  { symbol: '🦀', name: '螃蟹' },
  { symbol: '🐡', name: '河豚' },
  { symbol: '🐠', name: '热带鱼' },
  { symbol: '🐟', name: '鱼' },
  { symbol: '🐬', name: '海豚' },
  { symbol: '🐳', name: '鲸鱼' },
  { symbol: '🐋', name: '鲸' },
  { symbol: '🦈', name: '鲨鱼' },
  { symbol: '🐊', name: '鳄鱼' },
  { symbol: '🐅', name: '老虎' },
  { symbol: '🐆', name: '豹子' },
  { symbol: '🦓', name: '斑马' },
  { symbol: '🦍', name: '大猩猩' },
  { symbol: '🦧', name: '猩猩' },
  { symbol: '🐘', name: '大象' },
  { symbol: '🦛', name: '河马' },
  { symbol: '🦏', name: '犀牛' },
  { symbol: '🐪', name: '骆驼' },
  { symbol: '🐫', name: '双峰骆驼' },
  { symbol: '🦒', name: '长颈鹿' },
  { symbol: '🦘', name: '袋鼠' },
  { symbol: '🐃', name: '水牛' },
  { symbol: '🐂', name: '公牛' },
  { symbol: '🐄', name: '奶牛' },
  { symbol: '🐎', name: '马' },
  { symbol: '🐖', name: '猪' },
  { symbol: '🐏', name: '公羊' },
  { symbol: '🐑', name: '羊' },
  { symbol: '🦙', name: '羊驼' },
  { symbol: '🐐', name: '山羊' },
  { symbol: '🦌', name: '鹿' },
  { symbol: '🐕', name: '狗' },
  { symbol: '🐩', name: '贵宾犬' },
  { symbol: '🦮', name: '导盲犬' },
  { symbol: '🐕‍🦺', name: '服务犬' },
  { symbol: '🐈', name: '猫' },
  { symbol: '🐓', name: '公鸡' },
  { symbol: '🦃', name: '火鸡' },
  { symbol: '🦚', name: '孔雀' },
  { symbol: '🦜', name: '鹦鹉' },
  { symbol: '🦢', name: '天鹅' },
  { symbol: '🦩', name: '火烈鸟' },
  { symbol: '🕊️', name: '鸽子' },
  { symbol: '🐇', name: '兔子' },
  { symbol: '🦝', name: '浣熊' },
  { symbol: '🦨', name: '臭鼬' },
  { symbol: '🦡', name: '獾' },
  { symbol: '🦦', name: '水獭' },
  { symbol: '🦥', name: '树懒' },
  { symbol: '🐁', name: '小鼠' },
  { symbol: '🐿️', name: '松鼠' },
  { symbol: '🦔', name: '刺猬' },
  
  { symbol: '🌸', name: '樱花' },
  { symbol: '🌺', name: '芙蓉' },
  { symbol: '🌻', name: '向日葵' },
  { symbol: '🌷', name: '郁金香' },
  { symbol: '🌹', name: '玫瑰' },
  { symbol: '🥀', name: '枯萎花' },
  { symbol: '💐', name: '花束' },
  { symbol: '🌾', name: '稻穗' },
  { symbol: '🌱', name: '幼苗' },
  { symbol: '🌲', name: '常青树' },
  { symbol: '🌳', name: '落叶树' },
  { symbol: '🌴', name: '棕榈树' },
  { symbol: '🌵', name: '仙人掌' },
  { symbol: '🌿', name: '草本植物' },
  { symbol: '☘️', name: '三叶草' },
  { symbol: '🍀', name: '四叶草' },
  { symbol: '🎍', name: '门松' },
  { symbol: '🎋', name: '七夕树' },
  { symbol: '🍃', name: '叶子' },
  { symbol: '🍂', name: '落叶' },
  { symbol: '🍁', name: '枫叶' },
  { symbol: '🍄', name: '蘑菇' },
  { symbol: '🌰', name: '栗子' },
  
  // 食物和饮料
  { symbol: '🍇', name: '葡萄' },
  { symbol: '🍈', name: '甜瓜' },
  { symbol: '🍉', name: '西瓜' },
  { symbol: '🍊', name: '橘子' },
  { symbol: '🍋', name: '柠檬' },
  { symbol: '🍌', name: '香蕉' },
  { symbol: '🍍', name: '菠萝' },
  { symbol: '🥭', name: '芒果' },
  { symbol: '🍎', name: '红苹果' },
  { symbol: '🍏', name: '青苹果' },
  { symbol: '🍐', name: '梨' },
  { symbol: '🍑', name: '桃子' },
  { symbol: '🍒', name: '樱桃' },
  { symbol: '🍓', name: '草莓' },
  { symbol: '🥝', name: '猕猴桃' },
  { symbol: '🍅', name: '番茄' },
  { symbol: '🥥', name: '椰子' },
  { symbol: '🥑', name: '牛油果' },
  { symbol: '🍆', name: '茄子' },
  { symbol: '🥔', name: '土豆' },
  { symbol: '🥕', name: '胡萝卜' },
  { symbol: '🌽', name: '玉米' },
  { symbol: '🌶️', name: '辣椒' },
  { symbol: '🥒', name: '黄瓜' },
  { symbol: '🥬', name: '绿叶菜' },
  { symbol: '🥦', name: '西兰花' },
  { symbol: '🧄', name: '大蒜' },
  { symbol: '🧅', name: '洋葱' },
  { symbol: '🍄', name: '蘑菇' },
  { symbol: '🥜', name: '花生' },
  { symbol: '🌰', name: '栗子' },
  { symbol: '🍞', name: '面包' },
  { symbol: '🥐', name: '羊角面包' },
  { symbol: '🥖', name: '法棍' },
  { symbol: '🥨', name: '椒盐卷饼' },
  { symbol: '🥯', name: '贝果' },
  { symbol: '🥞', name: '煎饼' },
  { symbol: '🧇', name: '华夫饼' },
  { symbol: '🧀', name: '奶酪' },
  { symbol: '🍖', name: '排骨' },
  { symbol: '🍗', name: '鸡腿' },
  { symbol: '🥩', name: '牛排' },
  { symbol: '🥓', name: '培根' },
  { symbol: '🍔', name: '汉堡' },
  { symbol: '🍟', name: '薯条' },
  { symbol: '🍕', name: '披萨' },
  { symbol: '🌭', name: '热狗' },
  { symbol: '🥪', name: '三明治' },
  { symbol: '🌮', name: '墨西哥卷饼' },
  { symbol: '🌯', name: '墨西哥玉米饼' },
  { symbol: '🥙', name: '烤肉卷' },
  { symbol: '🧆', name: '炸豆丸子' },
  { symbol: '🥚', name: '鸡蛋' },
  { symbol: '🍳', name: '煎蛋' },
  { symbol: '🥘', name: '平底锅' },
  { symbol: '🍲', name: '火锅' },
  { symbol: '🥣', name: '碗勺' },
  { symbol: '🥗', name: '沙拉' },
  { symbol: '🍿', name: '爆米花' },
  { symbol: '🧈', name: '黄油' },
  { symbol: '🧂', name: '盐' },
  { symbol: '🥫', name: '罐头' },
  { symbol: '🍱', name: '便当' },
  { symbol: '🍘', name: '米饼' },
  { symbol: '🍙', name: '饭团' },
  { symbol: '🍚', name: '米饭' },
  { symbol: '🍛', name: '咖喱饭' },
  { symbol: '🍜', name: '拉面' },
  { symbol: '🍝', name: '意大利面' },
  { symbol: '🍠', name: '烤红薯' },
  { symbol: '🍢', name: '关东煮' },
  { symbol: '🍣', name: '寿司' },
  { symbol: '🍤', name: '天妇罗' },
  { symbol: '🍥', name: '鱼板' },
  { symbol: '🥮', name: '月饼' },
  { symbol: '🍡', name: '团子' },
  { symbol: '🥟', name: '饺子' },
  { symbol: '🥠', name: '幸运饼干' },
  { symbol: '🥡', name: '外卖盒' },
  { symbol: '🍦', name: '软冰淇淋' },
  { symbol: '🍧', name: '刨冰' },
  { symbol: '🍨', name: '冰淇淋' },
  { symbol: '🍩', name: '甜甜圈' },
  { symbol: '🍪', name: '饼干' },
  { symbol: '🎂', name: '生日蛋糕' },
  { symbol: '🍰', name: '蛋糕' },
  { symbol: '🧁', name: '纸杯蛋糕' },
  { symbol: '🥧', name: '派' },
  { symbol: '🍫', name: '巧克力' },
  { symbol: '🍬', name: '糖果' },
  { symbol: '🍭', name: '棒棒糖' },
  { symbol: '🍮', name: '布丁' },
  { symbol: '🍯', name: '蜂蜜' },
  { symbol: '🍼', name: '奶瓶' },
  { symbol: '🥛', name: '牛奶' },
  { symbol: '☕', name: '咖啡' },
  { symbol: '🍵', name: '茶' },
  { symbol: '🍶', name: '清酒' },
  { symbol: '🍾', name: '香槟' },
  { symbol: '🍷', name: '红酒' },
  { symbol: '🍸', name: '鸡尾酒' },
  { symbol: '🍹', name: '热带饮料' },
  { symbol: '🍺', name: '啤酒' },
  { symbol: '🍻', name: '干杯' },
  { symbol: '🥂', name: '碰杯' },
  { symbol: '🥃', name: '威士忌' },
  { symbol: '🥤', name: '吸管杯' },
  { symbol: '🧃', name: '饮料盒' },
  { symbol: '🧉', name: '马黛茶' },
  { symbol: '🧊', name: '冰块' },
  
  // 活动和运动
  { symbol: '⚽', name: '足球' },
  { symbol: '🏀', name: '篮球' },
  { symbol: '🏈', name: '橄榄球' },
  { symbol: '⚾', name: '棒球' },
  { symbol: '🥎', name: '垒球' },
  { symbol: '🎾', name: '网球' },
  { symbol: '🏐', name: '排球' },
  { symbol: '🏉', name: '英式橄榄球' },
  { symbol: '🥏', name: '飞盘' },
  { symbol: '🎱', name: '台球' },
  { symbol: '🪀', name: '悠悠球' },
  { symbol: '🏓', name: '乒乓球' },
  { symbol: '🏸', name: '羽毛球' },
  { symbol: '🏒', name: '曲棍球' },
  { symbol: '🏑', name: '草地曲棍球' },
  { symbol: '🥍', name: '长曲棍球' },
  { symbol: '🏏', name: '板球' },
  { symbol: '🪃', name: '回旋镖' },
  { symbol: '🥅', name: '球门' },
  { symbol: '⛳', name: '高尔夫球洞' },
  { symbol: '🪁', name: '风筝' },
  { symbol: '🏹', name: '弓箭' },
  { symbol: '🎣', name: '钓鱼竿' },
  { symbol: '🤿', name: '潜水镜' },
  { symbol: '🥊', name: '拳击手套' },
  { symbol: '🥋', name: '武术服' },
  { symbol: '🎽', name: '运动背心' },
  { symbol: '🛹', name: '滑板' },
  { symbol: '🛼', name: '旱冰鞋' },
  { symbol: '⛸️', name: '溜冰鞋' },
  { symbol: '🥌', name: '冰壶' },
  { symbol: '🎿', name: '滑雪板' },
  { symbol: '⛷️', name: '滑雪者' },
  { symbol: '🏂', name: '滑雪板' },
  { symbol: '🪂', name: '降落伞' },
  { symbol: '🏋️', name: '举重' },
  { symbol: '🤼', name: '摔跤' },
  { symbol: '🤸', name: '翻筋斗' },
  { symbol: '⛹️', name: '拍球' },
  { symbol: '🤺', name: '击剑' },
  { symbol: '🤾', name: '手球' },
  { symbol: '🏌️', name: '高尔夫' },
  { symbol: '🏇', name: '赛马' },
  { symbol: '🧘', name: '瑜伽' },
  { symbol: '🏄', name: '冲浪' },
  { symbol: '🏊', name: '游泳' },
  { symbol: '🤽', name: '水球' },
  { symbol: '🚣', name: '划船' },
  { symbol: '🧗', name: '攀岩' },
  { symbol: '🚵', name: '山地车' },
  { symbol: '🚴', name: '自行车' },
  { symbol: '🏆', name: '奖杯' },
  { symbol: '🥇', name: '金牌' },
  { symbol: '🥈', name: '银牌' },
  { symbol: '🥉', name: '铜牌' },
  { symbol: '🏅', name: '奖牌' },
  { symbol: '🎖️', name: '军功章' },
  { symbol: '🏵️', name: '花饰' },
  { symbol: '🎗️', name: '丝带' },
  { symbol: '🎫', name: '票' },
  { symbol: '🎟️', name: '入场券' },
  { symbol: '🎪', name: '马戏团' },
  { symbol: '🤹', name: '杂耍' },
  { symbol: '🎭', name: '戏剧面具' },
  { symbol: '🎨', name: '调色板' },
  { symbol: '🎬', name: '场记板' },
  { symbol: '🎤', name: '麦克风' },
  { symbol: '🎧', name: '耳机' },
  { symbol: '🎼', name: '乐谱' },
  { symbol: '🎹', name: '钢琴' },
  { symbol: '🥁', name: '鼓' },
  { symbol: '🎷', name: '萨克斯' },
  { symbol: '🎺', name: '小号' },
  { symbol: '🎸', name: '吉他' },
  { symbol: '🪕', name: '班卓琴' },
  { symbol: '🎻', name: '小提琴' },
  { symbol: '🎲', name: '骰子' },
  { symbol: '♟️', name: '国际象棋兵' },
  { symbol: '🎯', name: '靶心' },
  { symbol: '🎳', name: '保龄球' },
  { symbol: '🎮', name: '游戏手柄' },
  { symbol: '🎰', name: '老虎机' },
  { symbol: '🧩', name: '拼图' },
  
  // 旅行和地点
  { symbol: '🚗', name: '汽车' },
  { symbol: '🚕', name: '出租车' },
  { symbol: '🚙', name: '运动型多用途车' },
  { symbol: '🚌', name: '公交车' },
  { symbol: '🚎', name: '无轨电车' },
  { symbol: '🏎️', name: '赛车' },
  { symbol: '🚓', name: '警车' },
  { symbol: '🚑', name: '救护车' },
  { symbol: '🚒', name: '消防车' },
  { symbol: '🚐', name: '小巴' },
  { symbol: '🚚', name: '货车' },
  { symbol: '🚛', name: '拖车' },
  { symbol: '🚜', name: '拖拉机' },
  { symbol: '🛴', name: '滑板车' },
  { symbol: '🚲', name: '自行车' },
  { symbol: '🛵', name: '摩托车' },
  { symbol: '🏍️', name: '摩托车' },
  { symbol: '🚨', name: '警车灯' },
  { symbol: '🚔', name: '迎面驶来的警车' },
  { symbol: '🚍', name: '迎面驶来的公交车' },
  { symbol: '🚘', name: '迎面驶来的汽车' },
  { symbol: '🚖', name: '迎面驶来的出租车' },
  { symbol: '🚡', name: '缆车' },
  { symbol: '🚠', name: '山区缆车' },
  { symbol: '🚟', name: '单轨铁路' },
  { symbol: '🚃', name: '铁路客车' },
  { symbol: '🚋', name: '电车' },
  { symbol: '🚞', name: '山区铁路' },
  { symbol: '🚝', name: '单轨' },
  { symbol: '🚄', name: '高速列车' },
  { symbol: '🚅', name: '子弹头高速列车' },
  { symbol: '🚈', name: '轻轨' },
  { symbol: '🚂', name: '火车头' },
  { symbol: '🚆', name: '火车' },
  { symbol: '🚇', name: '地铁' },
  { symbol: '🚊', name: '有轨电车' },
  { symbol: '🚉', name: '车站' },
  { symbol: '✈️', name: '飞机' },
  { symbol: '🛫', name: '起飞' },
  { symbol: '🛬', name: '降落' },
  { symbol: '🛩️', name: '小飞机' },
  { symbol: '💺', name: '座位' },
  { symbol: '🛰️', name: '卫星' },
  { symbol: '🚀', name: '火箭' },
  { symbol: '🛸', name: '飞碟' },
  { symbol: '🚁', name: '直升机' },
  { symbol: '🛶', name: '独木舟' },
  { symbol: '⛵', name: '帆船' },
  { symbol: '🚤', name: '快艇' },
  { symbol: '🛳️', name: '客轮' },
  { symbol: '⛴️', name: '渡轮' },
  { symbol: '🛥️', name: '摩托艇' },
  { symbol: '🚢', name: '船' },
  { symbol: '⚓', name: '锚' },
  { symbol: '⛽', name: '汽油泵' },
  { symbol: '🚧', name: '施工' },
  { symbol: '🚦', name: '垂直交通灯' },
  { symbol: '🚥', name: '水平交通灯' },
  { symbol: '🚏', name: '公交车站' },
  { symbol: '🗺️', name: '世界地图' },
  { symbol: '🗿', name: '摩艾石像' },
  { symbol: '🗽', name: '自由女神像' },
  { symbol: '🗼', name: '东京塔' },
  { symbol: '🏰', name: '城堡' },
  { symbol: '🏯', name: '日本城堡' },
  { symbol: '🏟️', name: '体育馆' },
  { symbol: '🎡', name: '摩天轮' },
  { symbol: '🎢', name: '过山车' },
  { symbol: '🎠', name: '旋转木马' },
  { symbol: '⛲', name: '喷泉' },
  { symbol: '⛱️', name: '遮阳伞' },
  { symbol: '🏖️', name: '海滩遮阳伞' },
  { symbol: '🏝️', name: '荒岛' },
  { symbol: '⛰️', name: '山' },
  { symbol: '🏔️', name: '雪山' },
  { symbol: '🗻', name: '富士山' },
  { symbol: '🌋', name: '火山' },
  { symbol: '🏜️', name: '沙漠' },
  { symbol: '🏕️', name: '露营' },
  { symbol: '⛺', name: '帐篷' },
  { symbol: '🛤️', name: '铁路轨道' },
  { symbol: '🛣️', name: '高速公路' },
  { symbol: '🏗️', name: '建筑工地' },
  { symbol: '🏭', name: '工厂' },
  { symbol: '🏠', name: '房屋' },
  { symbol: '🏡', name: '带花园的房屋' },
  { symbol: '🏘️', name: '房屋建筑群' },
  { symbol: '🏚️', name: '废墟' },
  { symbol: '🏢', name: '办公楼' },
  { symbol: '🏬', name: '百货商店' },
  { symbol: '🏣', name: '日本邮局' },
  { symbol: '🏤', name: '邮局' },
  { symbol: '🏥', name: '医院' },
  { symbol: '🏦', name: '银行' },
  { symbol: '🏨', name: '酒店' },
  { symbol: '🏪', name: '便利店' },
  { symbol: '🏫', name: '学校' },
  { symbol: '🏩', name: '情人酒店' },
  { symbol: '💒', name: '婚礼' },
  { symbol: '🏛️', name: '古典建筑' },
  { symbol: '⛪', name: '教堂' },
  { symbol: '🕌', name: '清真寺' },
  { symbol: '🕍', name: '犹太教堂' },
  { symbol: '🕋', name: '克尔白' },
  { symbol: '⛩️', name: '神社' },
  { symbol: '🗾', name: '日本地图' },
  { symbol: '🎑', name: '赏月' },
  { symbol: '🏞️', name: '国家公园' },
  { symbol: '🌅', name: '日出' },
  { symbol: '🌄', name: '山间日出' },
  { symbol: '🌠', name: '流星' },
  { symbol: '🎇', name: '烟花' },
  { symbol: '🎆', name: '焰火' },
  { symbol: '🌇', name: '日落' },
  { symbol: '🌆', name: '黄昏城市' },
  { symbol: '🏙️', name: '城市风光' },
  { symbol: '🌃', name: '夜晚城市' },
  { symbol: '🌌', name: '银河' },
  { symbol: '🌉', name: '夜景桥梁' },
  { symbol: '🌁', name: '雾天' },
  
  // 物品和符号
  { symbol: '⌚', name: '手表' },
  { symbol: '📱', name: '手机' },
  { symbol: '📲', name: '带箭头的手机' },
  { symbol: '💻', name: '笔记本电脑' },
  { symbol: '⌨️', name: '键盘' },
  { symbol: '🖥️', name: '台式电脑' },
  { symbol: '🖨️', name: '打印机' },
  { symbol: '🖱️', name: '电脑鼠标' },
  { symbol: '🖲️', name: '轨迹球' },
  { symbol: '💽', name: '电脑光盘' },
  { symbol: '💾', name: '软盘' },
  { symbol: '💿', name: '光盘' },
  { symbol: '📀', name: 'DVD' },
  { symbol: '🧮', name: '算盘' },
  { symbol: '🎥', name: '摄像机' },
  { symbol: '🎞️', name: '电影胶片' },
  { symbol: '📽️', name: '电影放映机' },
  { symbol: '🎬', name: '场记板' },
  { symbol: '📺', name: '电视机' },
  { symbol: '📷', name: '相机' },
  { symbol: '📸', name: '带闪光灯的相机' },
  { symbol: '📹', name: '录像机' },
  { symbol: '📼', name: '录像带' },
  { symbol: '🔍', name: '放大镜' },
  { symbol: '🔎', name: '右斜放大镜' },
  { symbol: '🕯️', name: '蜡烛' },
  { symbol: '💡', name: '灯泡' },
  { symbol: '🔦', name: '手电筒' },
  { symbol: '🏮', name: '红灯笼' },
  { symbol: '🪔', name: '迪亚灯' },
  { symbol: '📔', name: '笔记本' },
  { symbol: '📕', name: '合上的书' },
  { symbol: '📖', name: '打开的书' },
  { symbol: '📗', name: '绿书' },
  { symbol: '📘', name: '蓝书' },
  { symbol: '📙', name: '橙书' },
  { symbol: '📚', name: '书本' },
  { symbol: '📓', name: '笔记本' },
  { symbol: '📒', name: '账本' },
  { symbol: '📃', name: '带卷边的页面' },
  { symbol: '📜', name: '卷轴' },
  { symbol: '📄', name: '页面' },
  { symbol: '📰', name: '报纸' },
  { symbol: '🗞️', name: '卷起来的报纸' },
  { symbol: '📑', name: '书签标签' },
  { symbol: '🔖', name: '书签' },
  { symbol: '🏷️', name: '标签' },
  { symbol: '💰', name: '钱袋' },
  { symbol: '💴', name: '日元' },
  { symbol: '💵', name: '美元' },
  { symbol: '💶', name: '欧元' },
  { symbol: '💷', name: '英镑' },
  { symbol: '💸', name: '带翅膀的钱' },
  { symbol: '💳', name: '信用卡' },
  { symbol: '🧾', name: '收据' },
  { symbol: '💹', name: '上涨趋势图表' },
  { symbol: '✉️', name: '信封' },
  { symbol: '📧', name: '电子邮件' },
  { symbol: '📨', name: '收到的信封' },
  { symbol: '📩', name: '带箭头的信封' },
  { symbol: '📤', name: '发件箱' },
  { symbol: '📥', name: '收件箱' },
  { symbol: '📦', name: '包裹' },
  { symbol: '📫', name: '关闭的邮箱(有旗)' },
  { symbol: '📪', name: '关闭的邮箱(无旗)' },
  { symbol: '📬', name: '开启的邮箱(有旗)' },
  { symbol: '📭', name: '开启的邮箱(无旗)' },
  { symbol: '📮', name: '邮筒' },
  { symbol: '🗳️', name: '投票箱' },
  { symbol: '✏️', name: '铅笔' },
  { symbol: '✒️', name: '黑钢笔尖' },
  { symbol: '🖋️', name: '钢笔' },
  { symbol: '🖊️', name: '圆珠笔' },
  { symbol: '🖌️', name: '画笔' },
  { symbol: '🖍️', name: '蜡笔' },
  { symbol: '📝', name: '备忘录' },
  { symbol: '💼', name: '公文包' },
  { symbol: '📁', name: '文件夹' },
  { symbol: '📂', name: '打开的文件夹' },
  { symbol: '🗂️', name: '索引分隔文件夹' },
  { symbol: '📅', name: '日历' },
  { symbol: '📆', name: '撕下的日历' },
  { symbol: '🗒️', name: '记事本' },
  { symbol: '🗓️', name: '螺旋装订日历' },
  { symbol: '📇', name: '索引卡片' },
  { symbol: '📈', name: '上涨图表' },
  { symbol: '📉', name: '下跌图表' },
  { symbol: '📊', name: '条形图' },
  { symbol: '📋', name: '剪贴板' },
  { symbol: '📌', name: '图钉' },
  { symbol: '📍', name: '圆图钉' },
  { symbol: '📎', name: '回形针' },
  { symbol: '🖇️', name: '连接的回形针' },
  { symbol: '📏', name: '直尺' },
  { symbol: '📐', name: '三角尺' },
  { symbol: '✂️', name: '剪刀' },
  { symbol: '🗃️', name: '卡片档案盒' },
  { symbol: '🗄️', name: '文件柜' },
  { symbol: '🗑️', name: '垃圾桶' },
  { symbol: '🔒', name: '上锁' },
  { symbol: '🔓', name: '解锁' },
  { symbol: '🔏', name: '带笔的锁' },
  { symbol: '🔐', name: '带钥匙的锁' },
  { symbol: '🔑', name: '钥匙' },
  { symbol: '🗝️', name: '老式钥匙' },
  { symbol: '🔨', name: '锤子' },
  { symbol: '🪓', name: '斧头' },
  { symbol: '⛏️', name: '镐' },
  { symbol: '⚒️', name: '锤子和镐' },
  { symbol: '🛠️', name: '锤子和扳手' },
  { symbol: '🗡️', name: '匕首' },
  { symbol: '⚔️', name: '交叉的剑' },
  { symbol: '🔫', name: '水枪' },
  { symbol: '🏹', name: '弓箭' },
  { symbol: '🛡️', name: '盾牌' },
  { symbol: '🔧', name: '扳手' },
  { symbol: '🔩', name: '螺母和螺栓' },
  { symbol: '⚙️', name: '齿轮' },
  { symbol: '🗜️', name: '夹钳' },
  { symbol: '⚖️', name: '天平' },
  { symbol: '🦯', name: '导盲杖' },
  { symbol: '🔗', name: '链接' },
  { symbol: '⛓️', name: '链条' },
]);